### ISSUE TITLE
add density txt file

### ISSUE THREAD

**Issue by shruthivis** [isblab/nurd#1]
add this to results or scripts directory

**Comment by shruthivis** [comment]
several files mentioned in the readme do not seem to be found in the repo (sampcon.sh, run_analysis_traj*, density.txt). Let's add the latest versions of these once we are done.

**Comment by shruthivis** [comment]
these files are not there still so reopening....

**Comment by shreyas-arvindekar** [comment]
density.txt files for MHR, MHM and NuDe are now added to scripts/analysis/pmi_analysis
