### ISSUE TITLE
Rearrangements and adding scripts

### ISSUE THREAD

**Issue by shruthivis** [isblab/nurd#2]
1. make folders in analysis dir e.g. chimera, xlviol 
2. modify readme according to newest runs 
3. add run_ana*, run_extrac*, sampcon with density txt to scripts/analysis subfolder 
4. update how we run the analysis scripts if necessary (e.g. contact_map script).

**Comment by shreyas-arvindekar** [comment]
Added the files, organised the scripts/analysis directory and updated the readme

**Comment by shruthivis** [comment]
references to mhm control run should be removed
